require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DefaultFormatter: progress
  DisplayCopNames: true
  ExtraDetails: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'vendor/**/*'

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '^# [^\n]+'

Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*.rb'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - 'lib/tasks/**/*.rake'
    - 'spec/**/*'

Naming/PredicateName:
  ForbiddenPrefixes:
    - is_

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Rails/DynamicFindBy:
  Enabled: false

Rails/SkipsModelValidations:
  AllowedMethods:
    - increment!
    - decrement!
    - touch

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/NestedGroups:
  Max: 5

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/Documentation:
  Enabled: false
